version: '3'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: adminroot
      MYSQL_DATABASE: nestjs
      MYSQL_USER: testuser
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
